-- Fox: Game  duration is about 10 minutes
local GAME_DURATION = 10 * 60

TUNING.BATTLE_ROYALE = {
    SPAWN_HEIGHT = 30,
    FALLING_SPEED = -10,

    GAME_DURATION = GAME_DURATION,
    WIN_DELAY = 10,

    PVP_SLOWDOWN = 0.75,
    PVP_SLOWDOWN_DURATION = 3,

    FOG = { 
        START_TIME = 0.2 * GAME_DURATION,
        SCALE_TIME = 0.6 * GAME_DURATION,
        SCALE_NUMS = 6,
        MIN_RANGE =  TILE_SCALE * 5.5,
    }
}

TUNING.PVP_DAMAGE_MOD = 1
TUNING.BASE_COOK_TIME = 0